spring:
  main:
    web-application-type: none
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

starbot:
  common:
    version:
      number: 1.0.0
      release-date: 2025-03-09